set(command "/home/dnanexus/cmake-3.11.0-Linux-x86_64/bin/cmake;-P;/home/dnanexus/TBB-prefix/src/TBB-stamp/download-TBB.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/home/dnanexus/cmake-3.11.0-Linux-x86_64/bin/cmake;-P;/home/dnanexus/TBB-prefix/src/TBB-stamp/verify-TBB.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/home/dnanexus/cmake-3.11.0-Linux-x86_64/bin/cmake;-P;/home/dnanexus/TBB-prefix/src/TBB-stamp/extract-TBB.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
