# -*- mode: makefile -*-
#
# Makefile definitions included by the top Makefile

# The macro below is expanded when 'realpath' is not built-in.
# Built-in 'realpath' is available on GNU Make 3.81.
realpath = $(shell cd $(1); pwd)

ROOT_SRCDIR    := $(call realpath, /mnt/build/workspace/root-release-6.14/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/sources/root_v6.14.00/root-6.14.00)
ROOT_OBJDIR    := $(call realpath, /mnt/build/workspace/root-release-6.14/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v6.14.00-cmake)

ifndef ROOT_SRCDIR
$(error Error determining ROOT_SRCDIR)
endif
ifndef ROOT_OBJDIR
$(error Error determining ROOT_OBJDIR)
endif

# The macro below strips off the source dir path to make a relative path name
stripsrc = $(subst $(ROOT_SRCDIR)/,,$(1))

# This macro creates the list of pcm files to be passed to a library
# dictionary generation step, something like
#    $(call pcm_rootcling_opt,$(TREELIBDEPM))
pcm_rootcling_opt = -m lib/libCore_rdict.pcm $(addprefix -m ,$(subst $(SOEXT),_rdict.pcm,$1))

# This macro returns the name of the pcm corresponding to a library
#    $(call pcmname,$(TREELIB))
pcmname = $(subst .$(SOEXT),_rdict.pcm,$1)

# This macro returns the list of pcm's that are needed for a package
#    $(call pcmdep,TREE)
# the argument is the upper case name of the library (see the Module.mk)
pcmdep = lib/libCore_rdict.pcm $(subst .$(SOEXT),_rdict.pcm,$($1LIBDEPM))

# This macro builds the rootmap name starting from the library full path
#    $(call rmfName, TREELIB)
# the argument is the upper case name of the library (see the Module.mk)
rmfName = $(dir $1)$(subst .$(SOEXT),.rootmap,$(notdir $1))

# This macro returns the arguments to be passed to rootcling to properly
# generate the rootmap file
#    $(call rootmapModule, TREELIB)
# the argument is the upper case name of the library (see the Module.mk)
rootmapModule = -rml $(notdir $1) -rmf $(call rmfName, $1)

# This macro returns the argument to be passed to rootcling to
# properly setup the pcm
#    $(call dictModule,TREE)
# the argument is the upper case name of the library (see the Module.mk)
dictModule = -s $($1LIB) $(call rootmapModule, $($1LIB)) $(call pcm_rootcling_opt, $($1LIBDEPM))

# This macro is used to setup the rule where the pcm depends on the
# dictionary and the library's dependent pcm's
#    $(call pcmrule,TREE)
# the argument is the upper case name of the library (see the Module.mk)
pcmrule = $(call pcmname, $($1LIB)): $(call pcmdep, $1) $($1DS)

noop = @true # "Do nothing really, this is just to make the rule stick"

ARCH           := linuxx8664gcc
HOST           := 

USECONFIG      := FALSE
MKLIBOPTIONS   := -v 6 14 00 

EXTRA_CFLAGS   := -Iinclude  -pipe -m64  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -std=c++11
USERCONF_CFLAGS:= 
EXTRA_CXXFLAGS := -Iinclude  -pipe -m64  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -std=c++11
USERCONF_CXXFLAGS:= 
EXTRA_LDFLAGS  := 
WERROR         := 
WINRTDEBUG     := no
CTORSINITARRAY := 
CXXMKDEPFLAGS  := 

GLBPATCHFLAGS  := 
EXTRA_AUTHFLAGS:=    

BINDIR         := $(ROOTSYS)/bin
LIBDIR         := $(ROOTSYS)/lib
INCDIR         := $(ROOTSYS)/include
ETCDIR         := $(ROOTSYS)/etc
MANDIR         := $(ROOTSYS)/man
DATADIR        := $(ROOTSYS)/.
ELISPDIR       := $(ROOTSYS)/emacs/site-lisp
TTFFONTDIR     := $(ROOTSYS)/fonts
MACRODIR       := $(ROOTSYS)/macros
SRCDIR         := $(ROOTSYS)/src
ICONPATH       := $(ROOTSYS)/icons
DOCDIR         := $(ROOTSYS)/.
TESTDIR        := $(ROOTSYS)/test
TUTDIR         := $(ROOTSYS)/tutorials
ACLOCALDIR     := $(ROOTSYS)/aclocal

BUILDX11       := yes
X11INCDIR      := $(filter-out /usr/include, )
X11LIBDIR      := -L/usr/lib/x86_64-linux-gnu
XPMLIBDIR      := -L/usr/lib/x86_64-linux-gnu
XPMLIB         := /usr/lib/x86_64-linux-gnu/libXpm.so
XFTLIB         := yes

BUILDCOCOA     := 
MACOSXVERS     := 
OSXSDK         := 
IOSVERS        := 
IOSSDK         := 

CXX11          := 
CXX14          := 
CXXMODULES     := OFF
LIBCXX         := 

EXPLICITLINK   := yes

ENABLETHREAD   := yes
OSTHREADFLAG   := -pthread
OSTHREADLIBDIR := 
OSTHREADLIB    := -lpthread

BUILTINFREETYPE:= yes

BUILTINPCRE    := yes

BUILTINUNURAN  := yes
UNURANLIBDIR   := 
UNURANLIBEXT   := UNURAN_LIBRARY-NOTFOUND
UNURANLIB      := UNURAN_LIBRARY-NOTFOUND
UNURANINCDIR   := $(filter-out /usr/include, UNURAN_INCLUDE_DIR-NOTFOUND)

BUILTINZLIB    := no
ZLIBLIBDIR     := 
ZLIBCLILIB     := /usr/lib/x86_64-linux-gnu/libz.so
ZLIBINCDIR     := $(filter-out /usr/include, /usr/include)

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

BUILTINLZ4     := 
LZ4LIBDIR      := 
LZ4CLILIB      := 
LZ4INCDIR      := $(filter-out /usr/include, )

BUILDGL        := yes
OPENGLLIBDIR   := 
OPENGLULIB     := /usr/lib/x86_64-linux-gnu/libGLU.so
OPENGLLIB      := /usr/lib/x86_64-linux-gnu/libGL.so
OPENGLINCDIR   := $(filter-out /usr/include, /usr/include)

BUILTINGL2PS   := no
GL2PSLIBDIR    := 
GL2PSLIB       := /usr/lib/libgl2ps.so
GL2PSINCDIR    := $(filter-out /usr/include, /usr/include)

BUILDLDAP      := yes
LDAPLIBDIR     := 
LDAPCLILIB     := /usr/lib/x86_64-linux-gnu/libldap.so
LDAPINCDIR     := $(filter-out /usr/include, /usr/include)

BUILDMYSQL     := yes
MYSQLLIBDIR    := 
MYSQLCLILIB    := 
MYSQLINCDIR    := $(filter-out /usr/include, /usr/include/mysql)

BUILDORACLE    := no
ORACLELIBDIR   := 
ORACLECLILIB   := ORACLE_LIBRARY_OCCI-NOTFOUND;ORACLE_LIBRARY_CLNTSH-NOTFOUND;ORACLE_LIBRARY_LNNZ-NOTFOUND
ORACLEINCDIR   := $(filter-out /usr/include, ORACLE_INCLUDE_DIR-NOTFOUND)

BUILDPGSQL     := yes
PGSQLLIBDIR    := 
PGSQLCLILIB    := 
PGSQLINCDIR    := $(filter-out /usr/include, )

BUILDSQLITE     := yes
SQLITELIBDIR    := 
SQLITECLILIB    := 
SQLITEINCDIR    := $(filter-out /usr/include, /usr/include)

BUILDSAPDB     := no
SAPDBLIBDIR    := 
SAPDBCLILIB    := 
SAPDBINCDIR    := $(filter-out /usr/include, )

BUILDODBC      := no
ODBCLIBDIR     := 
ODBCCLILIB     := 
ODBCINCDIR     := $(filter-out /usr/include, )

BUILDGEOCAD    := 
OCCLIBDIR      := 
OCCLIB         := 
OCCINCDIR      := $(filter-out /usr/include, )

BUILDQT        := yes
BUILDQTGSI     := 
QTLIBDIR       := /usr/lib/x86_64-linux-gnu
QTLIB          := 
QTINCDIR       := $(filter-out /usr/include, )
QTVERS	       := 
QTMOCEXE       := /usr/lib/x86_64-linux-gnu/qt4/bin/moc

BUILDRFIO      := no
SHIFTLIBDIR    := 
SHIFTLIB       := 
SHIFTINCDIR    := $(filter-out /usr/include, )
SHIFTCFLAGS    := 

BUILDCASTOR    := no
CASTORLIBDIR   := 
CASTORCLILIB   := 
CASTORINCDIR   := $(filter-out /usr/include, CASTOR_INCLUDE_DIR-NOTFOUND)
CASTORCFLAGS   := 

BUILDDAVIX      := yes
DAVIXLIBDIR     := 
DAVIXCLILIB     := /usr/lib/x86_64-linux-gnu/libxml2.so;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
DAVIXINCDIR     := $(filter-out /usr/include, /mnt/build/workspace/root-release-6.14/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v6.14.00-cmake/builtins/davix/DAVIX-prefix/include/davix)

BUILDDCAP      := 
DCAPLIBDIR     := 
DCAPLIB        := /usr/lib/libdcap.so
DCAPINCDIR     := $(filter-out /usr/include, /usr/include)

BUILDFTGL      := yes
FTGLLIBDIR     := 
FTGLLIBS       := FTGL
FTGLINCDIR     := $(filter-out /usr/include, /mnt/build/workspace/root-release-6.14/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/sources/root_v6.14.00/root-6.14.00/graf3d/ftgl/inc)
ifeq ($(BUILDFTGL), yes)
FTGLCPPFLAGS   := -DBUILTIN_FTGL
endif

BUILDGLEW      := yes
GLEWLIBDIR     := 
GLEWLIBS       := 
GLEWINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDGLEW), yes)
GLEWCPPFLAGS   := -DBUILTIN_GLEW
endif

BUILDGFAL      := yes
GFALLIBDIR     := 
GFALCLILIB     := /usr/lib/libgfal2.so
GFALINCDIR     := $(filter-out /usr/include, /usr/include/gfal2)
SRMIFCEINCDIR  := $(filter-out /usr/include, )
GLIB2INCDIR    := $(filter-out /usr/include, )

BUILDGLITE     := no
GLITELIBDIR    := 
GAWLIB         := 
GAW_CPPFLAGS   := $(filter-out /usr/include, )

BUILDMEMSTAT   := yes

BUILDBONJOUR   := yes
DNSSDLIBDIR    := 
DNSSDLIB       := /usr/lib/x86_64-linux-gnu/libdns_sd.so
DNSSDINCDIR    := $(filter-out /usr/include, )

BUILDCHIRP     := no
CHIRPLIBDIR    := 
CHIRPCLILIB    := CHIRP_LIBRARY-NOTFOUND
CHIRPINCDIR    := $(filter-out /usr/include, CHIRP_INCLUDE_DIR-NOTFOUND)

BUILDHDFS      := no
HDFSLIBDIR     := 
HDFSCLILIB     := 
HDFSINCDIR     := $(filter-out /usr/include, )
JNIINCDIR      := $(filter-out /usr/include, ) $(filter-out /usr/include, /linux)
JVMCLILIB      := 
JVMLIBDIR      := 

BUILDALIEN     := no
ALIENLIBDIR    := 
ALIENCLILIB    := 
ALIENINCDIR    := $(filter-out /usr/include, )

BUILDASIMAGE   := yes
BUILTINASIMAGE := ON
ASEXTRALIB     := /usr/lib/x86_64-linux-gnu/libgif.so;/usr/lib/x86_64-linux-gnu/libtiff.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libjpeg.so
ASEXTRALIBDIR  := 
ASJPEGINCDIR   := $(filter-out /usr/include, /usr/include)
ASPNGINCDIR    := $(filter-out /usr/include, /usr/include)
ASTIFFINCDIR   := $(filter-out /usr/include, /usr/include/x86_64-linux-gnu)
ASINCDIR       := $(filter-out /usr/include, )
ASLIB          := 
ASLIBDIR       := 

BUILDFPYTHIA6    := no
FPYTHIA6LIBDIR   := 
FPYTHIA6LIB      := PYTHIA6_LIBRARY-NOTFOUND
FPYTHIA6CPPFLAGS := 

BUILDFPYTHIA8    := yes
FPYTHIA8INCDIR   := $(filter-out /usr/include, )
FPYTHIA8LIBDIR   := 
FPYTHIA8LIB      := /opt/pythia8/lib/libpythia8.so

BUILDFFTW3     := yes
FFTW3LIBDIR    := 
FFTW3LIB       := 
FFTW3INCDIR    := $(filter-out /usr/include, )

BUILDFITSIO    := yes
CFITSIOLIBDIR  := 
CFITSIOLIB     := 
CFITSIOINCDIR  := $(filter-out /usr/include, )

BUILDGVIZ      := yes
GRAPHVIZLIBDIR := 
GRAPHVIZLIB    := 
GRAPHVIZINCDIR := $(filter-out /usr/include, )
GRAPHVIZCFLAGS := 

BUILDPYTHON    := yes
PYTHONLIBDIR   := 
PYTHONLIB      := /usr/lib/x86_64-linux-gnu/libpython2.7.so
PYTHONINCDIR   := $(filter-out /usr/include, /usr/include/python2.7)
PYTHONLIBFLAGS := 
PYTHONEXE      := 

BUILDRUBY      := no
RUBYLIBDIR     := 
RUBYLIB        := 
RUBYINCDIR     := $(filter-out /usr/include, )

BUILDXML       := yes
XMLLIBDIR      := 
XMLCLILIB      := /usr/lib/x86_64-linux-gnu/libxml2.so
XMLINCDIR      := $(filter-out /usr/include, /usr/include/libxml2)

HASXRD         := 
XRDINCDIR      := 
XRDLIBDIR      := 
EXTRA_XRDFLAGS := 
XRDVERSION     := 
HASXRDUTILS    := 
XRDINCPRIVATE  := 
BUILDNETXNG    := yes
BUILDXPROOFD   := 
BUILDXRDCLT    := 

SRPLIBDIR      := 
SRPLIB         := 
SRPINCDIR      := $(filter-out /usr/include, )

BUILDSRPUTIL   := 
SRPUTILLIBDIR  := 
SRPUTILLIB     := 
SRPUTILINCDIR  := $(filter-out /usr/include, )

AFSLIB         := 
AFSLIBDIR      := 
AFSINCDIR      := 
AFSEXTRACFLAGS := 
AFSSHARED      := 

ALLOCLIB       := 
ALLOCLIBDIR    := 

BUILDKRB5      := yes
KRB5LIB        := /usr/lib/x86_64-linux-gnu/libkrb5.so
KRB5LIBDIR     := 
KRB5INCDIR     := $(filter-out /usr/include, /usr/include/krb5)
KRB5INIT       := /usr/bin/kinit

COMERRLIB      := 
COMERRLIBDIR   := 

RESOLVLIB      := 

CRYPTOLIB      := -lcrypt
CRYPTOLIBDIR   := 

BUILDGLOBUS    := no
GLOBUSLIB      := 
GLOBUSLIBDIR   := 
GLOBUSINCDIR   := $(filter-out /usr/include, )

BUILDMONALISA  := no
MONALISALIBDIR := 
MONALISACLILIB := MONALISA_LIBRARY-NOTFOUND
MONALISAINCDIR := $(filter-out /usr/include, MONALISA_INCLUDE_DIR-NOTFOUND)

BUILDTBB       := 
TBBLIBDIR      := 
TBBLIB         := 
TBBINCDIR      := $(filter-out /usr/include, )

SSLLIB         := /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
SSLLIBDIR      := 
SSLINCDIR      := $(filter-out /usr/include, /usr/include)
SSLSHARED      := 

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

SHADOWFLAGS    := yes
SHADOWLIB      :=
SHADOWLIBDIR   :=

BUILDGENVECTOR := yes

BUILDMATHMORE  := yes
GSLFLAGS       := $(filter-out -I/usr/include, )
GSLLIBDIR      := 
GSLLIBS        := /mnt/build/workspace/root-release-6.14/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v6.14.00-cmake/lib/libgsl.a;/mnt/build/workspace/root-release-6.14/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v6.14.00-cmake/lib/libgslcblas.a
GSLVERSION     := 

BUILTINLLVM    := 
LLVMCONFIG     := 

BUILDROOFIT    := yes

BUILDMINUIT2   := yes

BUILDUNURAN    := yes

BUILDVC        := 
BUILDVDT       := 
AVXCXXFLAG     := 
SIMDCXXFLAGS   :=  
VCFLAGS        :=  

BUILDGDML      := yes

BUILDTABLE     := yes

BUILDTMVA      := yes

BUILDAFDSMGRD  := 
AFDSMGRDAPMON  := 

BUILDHTTP      := yes
USEFASCGI      := 
FASTCGIINCDIR  := 
ifeq ($(USEFASCGI), no)
FASTCGIFLAGS   := -DHTTP_WITHOUT_FASTCGI
endif

CPPUNIT        := 
GCCXML         := 

INSTALL        := cp -dpR
INSTALLDATA    := cp -dpR
INSTALLDIR     := mkdir -p
RSYNC          := rsync -au

BUILDR         := 
RLIBS          := 
RFLAGS         := 

ROOTDRPMREL    := 1
